version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: chat_postgres
    environment:
      POSTGRES_USER: osidev 
      POSTGRES_PASSWORD: osidev25  
      POSTGRES_DB: chatdb
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
